defaults: &defaults
  host: 127.0.0.1
  port: 27017
  database: glossy

development:
  <<: *defaults

test:
  <<: *defaults
  database: glossy_test

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOLAB_URI'] %>
